// FETCH
export const FETCH_SOME_DATA_REQUEST = 'FETCH_SOME_DATA_REQUEST';
export const FETCH_SOME_DATA_SUCCESS = 'FETCH_SOME_DATA_SUCCESS';
export const FETCH_SOME_DATA_ERROR = 'FETCH_SOME_DATA_ERROR';
